// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Vigneti.Data;
using Vigneti.Models;

namespace Vigneti.Migrations
{
    [DbContext(typeof(VineyardContext))]
    partial class VineyardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vigneti.Models.VineGrower", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FullName");

                    b.HasKey("ID");

                    b.ToTable("VineGrower");
                });

            modelBuilder.Entity("Vigneti.Models.Vineyard", b =>
                {
                    b.Property<int>("VineyardID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Dimension");

                    b.Property<double>("Humidity");

                    b.Property<int>("VineGrowerID");

                    b.Property<int>("WineID");

                    b.HasKey("VineyardID");

                    b.HasIndex("VineGrowerID");

                    b.HasIndex("WineID");

                    b.ToTable("Vineyard");
                });

            modelBuilder.Entity("Vigneti.Models.Wine", b =>
                {
                    b.Property<int>("WineID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Type");

                    b.HasKey("WineID");

                    b.ToTable("Wine");
                });

            modelBuilder.Entity("Vigneti.Models.Vineyard", b =>
                {
                    b.HasOne("Vigneti.Models.VineGrower", "VineGrower")
                        .WithMany("Vineyards")
                        .HasForeignKey("VineGrowerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Vigneti.Models.Wine", "Wine")
                        .WithMany("Vineyards")
                        .HasForeignKey("WineID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
